### ISSUE TITLE
qwerty layout in the Hungarian package

### ISSUE THREAD

**Issue by martonmiklos** [tmikkonen/sailfish-arrowboard#3]
Hey @tmikkonen 
I know this might be better to comment on openrepos but AFAIK you might not get notification about the comments there. So I have seen that you have released a newer version from the Hungarian arrowboard pack on the openrepos:
https://openrepos.net/content/tmi/hungarian-keyboard-arrows
Many thanks for it!

I have found more layouts in the archive than the previous one: it contains a qwerty layouts too. Were they added intentionally? To be honest we do not really use qwerty layouts we have qwertz everywhere. 

I have also noticed that the qwerz layouts got a (volt) suffix. What was the motivation behind this suffix? The volt itself have several meanings, and I was a bit confused when I first saw it. If you share with me what was the intention we might come up with some better naming. 
Thanks in advance!

**Comment by tmikkonen** [comment]
Hey,
And thanks!

If any qwerty-layouts slipped into the package, that was not intentional. I'll see and remove them later.

First I was only going to release the official dead key layout as a 2 & 4 arrow version. Then I figured I'd throw in the unofficial qwertz layout to avoid a situation where someone has gotten into the habbit of using it and would now hate to lose it (I don't know if this is realistic but you never know). As the unofficial and the official were both called Magyar, I just first named the unofficial Magyar(old), then Magyar(previous) but thought that English seemed a bit odd in there and checked a dictionary for 'former', 'previous' and also *cough*GT for 'former keyboard' and 'volt' seemed to fit them all. Of course, it would've been better to ask someone first but... yeah, my apologies :)

I'll gladly change the suffix to something more sensible! The idea was just to have something short to distinguish it from the now official Magyar keyboard. My intention was along the lines of 'previous/former keyboard', but whatever makes the most sense will suit just fine. I briefly thought using 'qwertz' earlier but the new official layout is also qwertz so that would not be the best choice.

**Comment by martonmiklos** [comment]
No qwerty slipped in, just I have missed it somehow.  

I think the word "volt" should be replaced by "régi". "Volt" is kind of similar to the "used to be" phrase in English while the "régi" rather means old or former whihc suits the current situation better.

**Comment by tmikkonen** [comment]
Ok, great! I'll replace "volt" with "régi" sometime before the weekend, maybe even tonight.
Köszi!

**Comment by tmikkonen** [comment]
Finally got this done. Sorry for the delay.
